version: '3'
services:
  webhooks:
    image: node:18
    container_name: webhooks
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    restart: unless-stopped
    networks:
      - cf-nw

volumes:
  node_modules:

networks:
  cf-nw:
    external: true
    name: cf-nw