version: '3'
services:
  webhooks:
    image: node:18
    container_name: webhooks
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped